"""empty message

Revision ID: 85d8acc4bf8d
Revises: b05f38c0f895
Create Date: 2022-09-26 18:29:20.601407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d8acc4bf8d'
down_revision = 'b05f38c0f895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shader_info_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Project', sa.String(length=200), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('Describe', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shader_info_model')
    # ### end Alembic commands ###
